export const COLLECTIBLES_POOL = [
  { symbol: "🗿", name: "Idol", tags: ["stone", "ancient", "statue"] },
  { symbol: "🧪", name: "Serum", tags: ["science", "glass", "liquid"] },
  { symbol: "🦉", name: "Feather", tags: ["forest", "animal", "soft"] },
  { symbol: "🔮", name: "Orb", tags: ["magic", "crystal", "glow"] },
  { symbol: "📜", name: "Scroll", tags: ["paper", "writing", "ancient"] },
  { symbol: "🗝️", name: "Key", tags: ["metal", "lock", "mystery"] },
  { symbol: "🪙", name: "Coin", tags: ["metal", "currency", "round"] },
  { symbol: "📦", name: "Crate", tags: ["wood", "container", "storage"] },
  { symbol: "💎", name: "Gem", tags: ["precious", "crystal", "shine"] },
  { symbol: "🧬", name: "Gene Strand", tags: ["dna", "science", "organic"] },
  { symbol: "⚗️", name: "Flask", tags: ["lab", "glass", "liquid"] },
  { symbol: "🕯️", name: "Candle", tags: ["light", "wax", "mystic"] },
  { symbol: "🪞", name: "Mirror", tags: ["reflection", "glass", "magic"] },
  { symbol: "🔧", name: "Wrench", tags: ["tool", "metal", "fix"] },
  { symbol: "📚", name: "Tome", tags: ["book", "ancient", "knowledge"] },
  { symbol: "🕰️", name: "Clock", tags: ["time", "mechanical", "vintage"] },
  { symbol: "🪓", name: "Axe", tags: ["weapon", "wood", "sharp"] },
  { symbol: "🪤", name: "Trap", tags: ["danger", "snare", "metal"] },
  { symbol: "🛡️", name: "Shield", tags: ["defense", "metal", "protection"] },
  { symbol: "⚔️", name: "Sword", tags: ["weapon", "metal", "battle"] },
  { symbol: "🧲", name: "Magnet", tags: ["metal", "pull", "science"] },
  { symbol: "🔋", name: "Battery", tags: ["energy", "power", "charge"] },
  { symbol: "🔗", name: "Chain", tags: ["metal", "binding", "linked"] },
  { symbol: "🪫", name: "Dead Cell", tags: ["power", "empty", "failure"] },
  { symbol: "🔬", name: "Microscope", tags: ["science", "glass", "zoom"] },
  { symbol: "🧼", name: "Soap", tags: ["clean", "bubbles", "soft"] },
  { symbol: "🪨", name: "Rock", tags: ["stone", "hard", "natural"] },
  { symbol: "🪵", name: "Log", tags: ["wood", "forest", "natural"] },
  { symbol: "🪰", name: "Fly", tags: ["insect", "buzz", "pest"] },
  { symbol: "🧃", name: "Juice Box", tags: ["liquid", "fruit", "carton"] },
  { symbol: "🪱", name: "Worm", tags: ["soil", "creature", "wiggle"] },
  { symbol: "🧱", name: "Brick", tags: ["stone", "construction", "heavy"] },
  { symbol: "🦴", name: "Bone", tags: ["skeleton", "animal", "white"] },
  { symbol: "🔦", name: "Flashlight", tags: ["light", "tool", "search"] },
  { symbol: "🩸", name: "Blood Vial", tags: ["red", "liquid", "biological"] },
  { symbol: "🧠", name: "Brain", tags: ["organ", "thought", "mind"] },
  { symbol: "🦷", name: "Tooth", tags: ["bone", "bite", "mouth"] },
  { symbol: "💊", name: "Pill", tags: ["medicine", "capsule", "health"] },
  { symbol: "🧃", name: "Potion", tags: ["magic", "liquid", "vial"] },
  { symbol: "🔭", name: "Telescope", tags: ["space", "science", "far"] },
  { symbol: "🧯", name: "Extinguisher", tags: ["fire", "safety", "tool"] },
  { symbol: "💡", name: "Lightbulb", tags: ["idea", "electric", "bright"] },
  { symbol: "🪄", name: "Wand", tags: ["magic", "spell", "wood"] },
  { symbol: "🪃", name: "Boomerang", tags: ["throw", "return", "weapon"] },
  { symbol: "🧵", name: "Thread", tags: ["string", "sewing", "fiber"] },
  { symbol: "🪡", name: "Needle", tags: ["sharp", "sewing", "metal"] },
  { symbol: "🧤", name: "Glove", tags: ["hand", "wear", "protect"] },
  { symbol: "👑", name: "Crown", tags: ["royalty", "gold", "status"] },
  { symbol: "🧣", name: "Scarf", tags: ["warm", "clothing", "fabric"] },
  { symbol: "🧦", name: "Sock", tags: ["foot", "clothing", "warm"] },
  { symbol: "🦺", name: "Vest", tags: ["safety", "clothing", "visible"] },
  { symbol: "🪖", name: "Helmet", tags: ["head", "protection", "metal"] },
  { symbol: "🎓", name: "Cap", tags: ["graduation", "head", "ceremony"] },
  { symbol: "🪙", name: "Medallion", tags: ["metal", "reward", "symbol"] },
  { symbol: "🎒", name: "Backpack", tags: ["carry", "bag", "explore"] },
  { symbol: "🗃️", name: "File Box", tags: ["archive", "paper", "store"] },
  { symbol: "🗂️", name: "Organizer", tags: ["folders", "sort", "documents"] },
  { symbol: "📁", name: "Folder", tags: ["paper", "store", "flat"] },
  { symbol: "📇", name: "Rolodex", tags: ["contacts", "cards", "office"] },
  { symbol: "🖇️", name: "Paperclip", tags: ["metal", "hold", "office"] },
  { symbol: "📎", name: "Binder Clip", tags: ["clamp", "paper", "stationery"] },
  { symbol: "🖊️", name: "Pen", tags: ["write", "ink", "tool"] },
  { symbol: "📝", name: "Notebook", tags: ["paper", "write", "record"] },
  { symbol: "📏", name: "Ruler", tags: ["measure", "tool", "length"] },
  { symbol: "📐", name: "Protractor", tags: ["angle", "geometry", "math"] },
  { symbol: "🧮", name: "Abacus", tags: ["count", "math", "classic"] },
  { symbol: "📊", name: "Chart", tags: ["graph", "data", "visual"] },
  { symbol: "📉", name: "Down Graph", tags: ["decline", "stats", "loss"] },
  { symbol: "📈", name: "Up Graph", tags: ["growth", "stats", "profit"] },
  { symbol: "🔒", name: "Padlock", tags: ["secure", "metal", "key"] },
  { symbol: "🔓", name: "Unlocked", tags: ["open", "access", "security"] },
  { symbol: "🛠️", name: "Toolbox", tags: ["repair", "tools", "store"] },
  { symbol: "🧰", name: "Utility Box", tags: ["tools", "box", "carry"] },
  { symbol: "🪛", name: "Screwdriver", tags: ["tool", "metal", "rotate"] },
  { symbol: "🔩", name: "Bolt", tags: ["metal", "fasten", "tool"] },
  { symbol: "🧱", name: "Foundation Brick", tags: ["structure", "base", "build"] },
  { symbol: "🪢", name: "Knot", tags: ["rope", "tie", "secure"] },
  { symbol: "🪝", name: "Hook", tags: ["catch", "metal", "grab"] },
  { symbol: "🔍", name: "Magnifier", tags: ["zoom", "inspect", "glass"] },
  { symbol: "📡", name: "Antenna", tags: ["signal", "tech", "wave"] },
  { symbol: "🧿", name: "Amulet", tags: ["protect", "magic", "wear"] },
  { symbol: "🪆", name: "Nesting Doll", tags: ["toy", "hidden", "wood"] },
  { symbol: "🪅", name: "Pinata", tags: ["candy", "hit", "paper"] },
  { symbol: "🪗", name: "Accordion", tags: ["music", "instrument", "fold"] },
  { symbol: "🎺", name: "Trumpet", tags: ["brass", "music", "loud"] },
  { symbol: "🥁", name: "Drum", tags: ["beat", "music", "rhythm"] },
  { symbol: "🎻", name: "Violin", tags: ["strings", "music", "bow"] },
  { symbol: "🎷", name: "Saxophone", tags: ["jazz", "brass", "tone"] },
  { symbol: "🪕", name: "Banjo", tags: ["strings", "music", "folk"] },
  { symbol: "🎸", name: "Guitar", tags: ["rock", "strings", "instrument"] },
  { symbol: "🎮", name: "Controller", tags: ["game", "input", "tech"] },
  { symbol: "🧭", name: "Compass", tags: ["direction", "navigation", "tool"] },
  { symbol: "🗺️", name: "Map", tags: ["explore", "paper", "directions"] },
  { symbol: "⛏️", name: "Pickaxe", tags: ["mine", "tool", "stone"] }
];